### ISSUE TITLE
[Feature Request] Support for Nested Categories Menus

### ISSUE THREAD

**Issue by ryanpato** [complexlogic/big-launcher#20]
Currently, Big Launcher allows for menus and entries, but I’d like to have a way to create a sub-category within a menu if possible. 

For example, instead of launching an emulator (e.g. DuckStation, Dolphin) and using their differing user-interfaces, I'd like to be taken to a sub-folder where my games per the given platform could be displayed as entry (these would be populated by a script). I believe this concept is potentially useful outside of this game/emulator example though.

I can work around this by adding a unique menu, but I'd prefer my menu to be higher level categories like you created 'media', 'games'.

**Example structure:**

```yml
menu:
   
  - title: "Media"
    entries:
      - title: "Kodi"
        command: ""

  - title: "Games"
    entries:
      - title: "PSX"
        icon: "assets/psx.png"
        entries:
          - title: "Spyro"
            icon: "assets/psx/covers/spyro.png"
            command: "duckstation --boot spyro"

          - title: "Crash Bandicoot"
            icon: "assets/psx/covers/crash.png"
            command: "duckstation --boot crash"

      - title: "GameCube"
        icon: "assets/gamecube.png"
        entries:
          - title: "Super Mario Sunshine"
            icon: "assets/gamecube/covers/mariosunshine.png"
            command: "dolphin --boot Super_Mario_Sunshine"

          - title: "The Legend of Zelda: The Wind Waker"
            icon: "assets/gamecube/covers/windwaker.png"
            command: "dolphin --boot Wind_Waker"
```
